### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by david-dilorenzo** [valcker/similar_text-ruby#1]
Could the author specify which license is the similar_text gem released under? I plan to use the gem inside a software project, and I also have to consider such issues.

thank you

**Comment by valcker** [comment]
Hi David,

I didn't really think about licensing before as the package is absolutely open and free for use for me. I'm thinking about GPL v2 or BSD, is it OK for you?

**Comment by david-dilorenzo** [comment]
BSD is perfect, as it is compatible with nearly everything.
If you want to use the GPL, could you please specify GPL v2 or later, and not just GPL v2? Otherwise it would be incompatible with other GPL v3 gems I am currently using.

**Comment by valcker** [comment]
BSD License file pushed in 1806bcf8c6. I didn't have time to rebuild a gem though, will try to do in a couple of days.

**Comment by david-dilorenzo** [comment]
Thank you, valcker
